\c tweets
REFRESH MATERIALIZED VIEW CONCURRENTLY fintweet.top_users;
REFRESH MATERIALIZED VIEW CONCURRENTLY fintweet.top_cashtags;
REFRESH MATERIALIZED VIEW CONCURRENTLY fintweet.top_hashtags;
REFRESH MATERIALIZED VIEW CONCURRENTLY fintweet.c;